site_name: SciStream
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - Guides:
    - User Guide: guides/user-guide.md
    - Authentication: guides/authentication.md
    - Developer Guide: guides/developer-guide.md
    - Tutorials: guides/tutorials.md
  - Reference:
    - Changelog: reference/changelog.md
    - FAQ: reference/faq.md
    - Troubleshooting: reference/troubleshooting.md