======================================
Scistream Client Authentication Workflow
======================================

Making a request without Local Credentials
------------------------------------------

**Case A: Scistream Server Does Not Require Authentication (Default Case)**

- *Server Command*::

    python src/s2cs.py

- *Expected Behavior*:
    - The client sends the request without needing to login.
    - The server processes the request without any authentication error.

- *Client Request*::

    python src/s2uc.py prod-req

- *Screenshots Required*:
    - Server setup in default mode (without scope_ID).
    - Client command execution.
    - Successful response from the server.

**Case B: Server Requires Authentication**

- *Server Command*::

    python src/s2cs.py --scope scope_ID

- *Expected Behavior*:
    - The client sends the request without login.
    - The server throws an error indicating that it requires authentication.

- *Client Request*::

    python src/s2uc.py prod-req

- *Screenshots Required*:
    - Server setup with scope_ID indicating the need for authentication.
    - Client command execution without credentials.
    - Server response/error indicating the need for authentication.
